apiVersion: v1
kind: ConfigMap
metadata:
  name: taskflow-config
  namespace: taskflow
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:8080"
  APP_NAME: "TaskFlow"
  APP_VERSION: "1.0.0"
  DATABASE_TIMEOUT: "30"