apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: taskflow-base

resources:
- namespace.yaml
- secret.yaml
- configmap.yaml
- postgres.yaml
- api.yaml
- frontend.yaml
- services.yaml
- ingress.yaml