apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-postgres
  namespace: taskflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskflow-postgres
  template:
    metadata:
      labels:
        app: taskflow-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        imagePullPolicy: Always
        env:
        - name: POSTGRES_DB
          value: "taskflowdb"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: taskflow-secrets
              key: postgres-username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: taskflow-secrets
              key: postgres-password
        ports:
        - containerPort: 5432
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
        livenessProbe:
          exec:
            command:
              - pg_isready
              - -U
              - taskflow
              - -d
              - taskflowdb
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
              - pg_isready
              - -U
              - taskflow
              - -d
              - taskflowdb
          initialDelaySeconds: 10
          periodSeconds: 15
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        emptyDir: {}
