apiVersion: v1
kind: Secret
metadata:
  name: taskflow-secrets-dev
  namespace: taskflow-dev
type: Opaque
data:
  # Base64 encoded values
  postgres-username: dGFza2Zsb3c=  # taskflow
  postgres-password: dGFza2Zsb3cxMjM=  # taskflow123
  connection-string: SG9zdD10YXNrZmxvdy1wb3N0Z3Jlcy1kZXY7RGF0YWJhc2U9dGFza2Zsb3dkYi1kZXY7VXNlcm5hbWU9dGFza2Zsb3c7UGFzc3dvcmQ9dGFza2Zsb3cxMjM=